### ISSUE TITLE
Receive_from

### ISSUE THREAD

**Issue by driesnuttin25** [JelleClaes2/UDP_TCP_project#3]
Would it be possible to add a certain character or an end line at the end of your send function. This would make it possible for me to check when you're done sending and make it so we don't rely on all  the numbers to be sent to the client side which eliminates errors.
This is the code in question.

uint16_t sendNumber(int internet_socket,struct sockaddr_storage client_internet_address,socklen_t client_internet_address_length,int number_of_bytes_send){
    uint16_t number = 0;
    uint16_t net_num = htons(number);
    uint16_t highestNumber = 0;

    //loop 42 times
    for(int i=0;i<42;i++){
        number = randomNumber();//generate a random number
        if(number > highestNumber){
            highestNumber = number;//keep track of the highest number
        }
        number_of_bytes_send = sendto( internet_socket, &net_num, sizeof(net_num), 0, (struct sockaddr *) &client_internet_address, client_internet_address_length );//send the number
        if( number_of_bytes_send == -1 )
        {
            perror( "sendto" );
        }
    }
    return highestNumber;
}

**Comment by JelleClaes2** [comment]
Isue was resolved together new method found
